In [1]:
import numpy as np

In [2]:
a=[10,20,30,40]
type(a)

list

In [3]:
x = np.array(a)
print(x)

[10 20 30 40]


In [4]:
type(x)

numpy.ndarray

In [10]:
a=[1,2,3,4]
b=[10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [12]:
a=[1,2,3,4]
b=[10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [15]:
x = np.array([1,2,3,4],dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [16]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [20]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [22]:
x = np.random.rand(2,5)
print(x)


[[0.41545587 0.19598074 0.48394193 0.55410236 0.85904997]
 [0.75081304 0.01074122 0.69035578 0.83157422 0.1133875 ]]


In [27]:
np.random.rand
np.random.randint(1,20, size=(3,3))

array([[ 3,  8, 15],
       [13, 15, 15],
       [11,  9, 18]], dtype=int32)

In [28]:
np.random.randint
np.random.randn(2,5)

array([[ 0.08295984,  0.32626402, -0.08490169,  0.16743469,  0.62145454],
       [ 1.10135659,  1.07831344,  0.41271084, -1.39658884, -1.06471494]])

In [29]:
np.random.choice([2,3,4,7,8,10])

np.int64(2)

In [30]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [34]:
np.ones((3,3))*20

array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]])

In [40]:
x = np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [42]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [43]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
a=[10,20,30,40,50]
x=np.array(a)
print(x)

[10 20 30 40 50]


In [46]:
x.ndim

1

In [47]:
b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [48]:
y.ndim

2

In [49]:
y.shape

(2, 5)

In [51]:
y.size

10

In [52]:
a=np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [53]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [55]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
a

array([ 3,  6,  9, 12])

In [57]:
x.size

15

In [58]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [59]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [60]:
y=x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [61]:
z=np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [62]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])