In [40]:
import numpy as np

In [41]:
a=[10,20,30,40]
type(a)

list

In [42]:
x = np.array(a)
print(x)

[10 20 30 40]


In [43]:
type(x)

numpy.ndarray

In [44]:
a=[1,2,3,4]
b=[10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [45]:
a=[1,2,3,4]
b=[10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [46]:
x = np.array([1,2,3,4],dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [47]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [48]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [51]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [52]:
x = np.random.rand(2,5)
print(x)


[[0.12685418 0.45236451 0.00266722 0.81459951 0.54497856]
 [0.32705077 0.11714026 0.94268238 0.7793693  0.57144105]]


In [53]:
np.random.rand
np.random.randint(1,20, size=(3,3))

array([[14, 14, 11],
       [ 9,  5,  9],
       [ 7, 14, 16]], dtype=int32)

In [54]:
np.random.randint
np.random.randn(2,5)

array([[ 1.52480514, -1.35225847, -0.61598054, -0.07664382,  0.46012508],
       [ 2.17130251,  0.34122306, -1.50444852, -1.55447882,  0.82931908]])

In [55]:
np.random.choice([2,3,4,7,8,10])

np.int64(10)

In [56]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [57]:
np.ones((3,3))*20

array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]])

In [58]:
x = np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [59]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [60]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [61]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [62]:
a=[10,20,30,40,50]
x=np.array(a)
print(x)

[10 20 30 40 50]


In [63]:
x.ndim

1

In [64]:
b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [65]:
y.ndim

2

In [66]:
y.shape

(2, 5)

In [67]:
y.size

10

In [68]:
a=np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [69]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [70]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
a

array([ 3,  6,  9, 12])

In [72]:
x.size

15

In [73]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [74]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [75]:
y=x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [76]:
z=np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [77]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [78]:
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
x[1][2]

np.int64(6)

In [80]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [81]:
import numpy as np

a=np.arange(1,6)
b=np.arange(6,11)
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [82]:
x= np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [83]:
x=np.hstack((a,b))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [84]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [86]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [87]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [88]:
import numpy as np
a=np.arange(10,21,2)
b=np.array([[2],[2]])
print(a)

[10 12 14 16 18 20]


In [89]:
print(b)

[[2]
 [2]]


In [90]:
z=a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [91]:
a=np.arange(10,21,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [92]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [93]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [94]:
a=np.ones((3,3))
b=np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [95]:
print(b)

[2]


In [96]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [97]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [98]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [99]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [100]:
a-1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [101]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [102]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [103]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [104]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [105]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
a=np.arange(5,15,2)
print(a)

[ 5  7  9 11 13]


In [107]:
np.mean(a)

np.float64(9.0)

In [108]:
np.median(a)

np.float64(9.0)

In [109]:
np.std(a)

np.float64(2.8284271247461903)

In [110]:
a=np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [111]:
print(np.min(a,axis=0))

[1 3]


In [112]:
print(np.min(a,axis=1))

[1 3]


In [113]:
print(np.max(a,axis=1))

[6 4]


In [114]:
print(np.max(a,axis=0))

[4 6]


In [116]:
a=np.array([1,4,3,10,20])
x=np.sort(a,kind='mergesort')
print(x)

[ 1  3  4 10 20]


In [117]:
A=np.arange(0,9).reshape(3,3)
B=np.ones((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [118]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [119]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [121]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])